version: 1
applications:
  - appRoot: client
  - backend: 
      phases:
        build:
          commands:
           - amplifyPush --simple
  - frontend:
      phases:
        prebuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
            - cd client
            - npm run build
      artifacts:
        baseDirectory: /client/build
        files:
          - '**/*'
      cache:
        paths:
          - client/node_modules/**/*